version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: unoesc_postgres_db
    environment:
      POSTGRES_USER: unoesc_user
      POSTGRES_PASSWORD: unoesc_password
      POSTGRES_DB: unoesc_academic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: